### ISSUE TITLE
GUI incorrect on iPads

### ISSUE THREAD

**Issue by SuperArcherG** [JohnnyHowe/drifto-pages#1]
The GUI does not work properly on iPads.![image](https://user-images.githubusercontent.com/78567389/210609668-d981395e-670d-4004-949d-6b4f9c7359f4.png)![image](https://user-images.githubusercontent.com/78567389/210609708-9cfd8d41-a130-4ee9-9bda-5bfaa8153e1d.png)

**Comment by JohnnyHowe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI scaling on wider devices terrible](https://trello.com/c/libUpiVm/282-ui-scaling-on-wider-devices-terrible)
