### ISSUE TITLE
Falling through map

### ISSUE THREAD

**Issue by CuddlyInsomniac** [JohnnyHowe/drifto-pages#2]
![3EBFB8CD-EE0D-46DD-9ED3-EE88D5B32164](https://user-images.githubusercontent.com/123155600/213652990-06d0295c-000c-4838-9267-bdf7851eba70.png)

Was playing on Indusso when I suddenly fell through the map

**Comment by JohnnyHowe** [comment]
Well that's not good. I'll take a look into it

**Comment by JohnnyHowe** [comment]
I was finally able to reproduce it and have found a fix.
It will be a part of the next major update
