### ISSUE TITLE
Controls, Old Terrain & Surface Issues

### ISSUE THREAD

**Issue by PrizeGotti** [JohnnyHowe/drifto-pages#3]
A lot of changes in this version have caused a number of issues;

After a while the game seems to forget I have my thumb on the screen and will act as if I’m no longer touching it until I remove my thumb and touch the screen again.

In Touge I am often seeing old terrain floating in the background since this recent update. While trees no longer spawn in the middle of the road, it looks like this graphical issue has taken its place.

Now the big one, in Indusso, the section of roundabout where you drive straight over has the wrong status applied to the surface and it thinks it’s driving on dirt. This is apparent from the smoke turning to mud trails and the fact it stops adding points during this section.

**Comment by JohnnyHowe** [comment]
The indusso roundabout issue will definitely be fixed in the next update (scheduled for 30/1/23).
I didn't know about the other two issues though.

For the old terrain issue on touge, is this after the hairpin or elsewhere? (see image)
![drifto-old-track-visible-on-hairpin](https://user-images.githubusercontent.com/29498897/213797455-2d6a8a69-472a-4c98-bf5e-4c4350c587c9.png)

**Comment by PrizeGotti** [comment]
Yes that picture is a pretty perfect replication of what I’m seeing. I don’t recall ever seeing it previously, but now it’s almost every run.

**Comment by JohnnyHowe** [comment]
Brilliant! A fix for this is planned already.
![mountain_comparison](https://user-images.githubusercontent.com/29498897/213799798-2c604718-25ef-460f-90e0-c9a4819165bb.png)

Credit to @nick-ziv for the idea

**Comment by JohnnyHowe** [comment]
![image](https://github.com/JohnnyHowe/drifto-pages/assets/29498897/78f2eed1-6dc1-4d78-8688-e66a8fc9cd29)
Made the fix. Will be available in beta currently. Promoting to production very soon
