### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Onosheetz** [JohnnyHowe/drifto-pages#4]
Hey I don’t know if you are aware of this issue but no matter how high I get my score the leaderboard always shows me as 3rd place, from roughly 7k to now 16k I have been number 3 on the leaderboard and it seems as though its not actually possible to get first. I know that this is not a big issue and I know you probably have a lot on your plate regarding fixes to your game so no rush. I look forward to seeing how this game develops as I continue to play.

**Comment by jackdrinkall** [comment]
I am also having this issue. Was #193 and more than quadrupled my best and I’m still 193
